### PR TITLE
feat: better version tags

### PR DESCRIPTION
**Pull request by raphaelcoeffic**

### CODE REVIEW

**Comment by pfeerick** [comment]
shall we see if it works? :rofl:

**Comment by pfeerick** [comment]
Not ideal, just a little better than current state.

 IIRC the way it worked is the nightly action sets the suffix for itself,
and for PRS and tagged releases build-gh checks env tags for git reference
info. For cloud build,  maybe the text from the version picker dropdown can
be used? Otherwise, yeah, have probably to construct the version tag  from
the git tag (again).

**Comment by raphaelcoeffic** [comment]
The main change now is to use `tools/build-gh.sh` instead of the self crafted and embedded script that was used before as well passing the proper env vars similar to what is done with GH actions (nightly -> EDGETX_VERSION_SUFFIX=nightly; anything else: EDGETX_VERSION_SUFFIX=cloudbuild; EDGETX_VERSION_TAG=[exact release tag as in targets.json])

The only thing I'm not quite sure is whether we pass `2.10.0-rc3` or `v2.10.0-rc3` as version tag on GH.

**Comment by pfeerick** [comment]
Normally has the v... i.e.
+ EDGETX_VERSION_TAG=v2.10.0-rc3

i.e. see the log from a tagged build (companion build uses the same logic)
https://github.com/EdgeTX/edgetx/actions/runs/8533248760/job/23375666944

**Pull request merged**
